apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myd
  name: myd
spec:
  replicas: 5
  selector:
    matchLabels:
      app: myd
  template:
    metadata:
      labels:
        app: myd
    spec:
      containers:
      - image: prasadparit0611/web-server-image:v1
        name: web-server-image
